CREATE TABLE CUSTOMER(
CUSTOMER_ID NUMBER(5) NOT NULL,
CUSTOMER_FIRST_NAME VARCHAR2(45) NOT NULL,
CUSTOMER_LAST_NAME VARCHAR2(45) NOT NULL,
LOGIN VARCHAR2(15) NOT NULL,
PASSWORD CHAR(250) NOT NULL,
CUSTOMER_EMAIL VARCHAR2(45) NOT NULL,
CUSTOMER_PHONE_NUMBER VARCHAR2(45) NOT NULL,
DELIVERY_ID NUMBER(5),
ORDERS_ID  NUMBER(5)
);

CREATE TABLE ORDERS(
ORDERS_ID NUMBER(5) NOT NULL,
ORDERS_COMMENT VARCHAR(255),
ORDERS_DISCOUNT VARCHAR2(30)
);

CREATE TABLE CATEGORIES(
CATEGORY_ID  NUMBER(5) NOT NULL,
CATEGORY_NAME VARCHAR2(30) NOT NULL
);

CREATE TABLE PRODUCT(
PRODUCT_ID  NUMBER(5) NOT NULL,
PRODUCT_NAME VARCHAR2(30) NOT NULL,
PRODUCT_PRICE NUMBER(11,2) NOT NULL,
PRODUCT_DESCRIPTION VARCHAR2(255),
PRODUCT_PICTURE BLOB,
CATEGORY_ID NUMBER(5) NOT NULL);

CREATE TABLE DELIVERY(
DELIVERY_ID NUMBER(5) NOT NULL,
DELIVERY_CITY VARCHAR2(45) NOT NULL,
DELIVERY_STREET VARCHAR2(45) NOT NULL,
DELIVERY_HOME VARCHAR2(15) NOT NULL,
DELIVERY_APARTMENTS VARCHAR2(10)
);

CREATE SEQUENCE ID_SEQUENCE
START WITH 1
INCREMENT BY 1
NOMAXVALUE;

ALTER TABLE CUSTOMER ADD CONSTRAINT CUSTOMER_ID_PK PRIMARY KEY (CUSTOMER_ID);
ALTER TABLE PRODUCT ADD CONSTRAINT PRODUCT_ID_PK PRIMARY KEY (PRODUCT_ID);
ALTER TABLE CATEGORIES ADD CONSTRAINT CATEGORY_ID_PK PRIMARY KEY (CATEGORY_ID);
ALTER TABLE ORDERS ADD CONSTRAINT ORDERS_ID_PK PRIMARY KEY (ORDERS_ID);
ALTER TABLE DELIVERY ADD CONSTRAINT DELIVERY_ID_PK PRIMARY KEY (DELIVERY_ID);
ALTER TABLE CUSTOMER ADD CONSTRAINT CUST_AD_FK FOREIGN KEY (DELIVERY_ID) REFERENCES DELIVERY (DELIVERY_ID);
ALTER TABLE CUSTOMER ADD CONSTRAINT CUST_ORD_ID_FK FOREIGN KEY (ORDERS_ID) REFERENCES ORDERS (ORDERS_ID);
ALTER TABLE PRODUCT ADD CONSTRAINT PROD_CAT_FK FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES (CATEGORY_ID);

